version: '3'
services:
    client-api:
        container_name: client-api
        build:
            dockerfile: Dockerfile
            context: ./client-api
        ports:
          - '5000:80'
        depends_on: 
            - product-api
        networks:
            - simplenet
    product-api:
        container_name: product-api
        build:
            dockerfile: Dockerfile
            context: ./product-api
        ports:
          - '5001:80'
        networks:
            - simplenet
networks:
    simplenet: